# Generated by Django 4.2 on 2023-07-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=255)),
                ('rating', models.IntegerField(null=True)),
                ('releaseyear', models.IntegerField(null=True)),
                ('comments', models.TextField(max_length=255)),
            ],
        ),
    ]
