# Generated by Django 4.2 on 2023-07-31 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuffapp', '0002_author_tag_remove_moviedetails_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviename', to='moviebuffapp.author'),
        ),
    ]
