# Generated by Django 4.2 on 2023-08-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuffapp', '0002_artist_moviedetails_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='mini_bio',
            field=models.TextField(default='Promising Actor'),
        ),
    ]
