# Generated by Django 4.2 on 2023-08-01 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuffapp', '0003_rename_post_review_movie_alter_moviedetails_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviename', to='moviebuffapp.author'),
        ),
    ]
