# Generated by Django 4.2 on 2023-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuffapp', '0004_remove_moviedetails_author_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
