# Generated by Django 4.2 on 2023-08-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebuffapp', '0005_rename_text_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='avg_rating',
            field=models.IntegerField(default=1),
        ),
    ]
